### ISSUE TITLE
Is there any documentation for Athec?

### ISSUE THREAD

**Issue by likai-kang** [yilangpeng/athec#1]
Hello, I'm recently interested in measuring aesthetic attributes for shopping images, and surprisingly find Athec while the codes of precious researches to measure aesthetics are not publicly available.

However, I could not find a documentation for it. I wonder whether there is a detailed description for the API?

**Comment by yilangpeng** [comment]
Thank you for the interest. You can find the relevant annotations in the .py scripts and also in the paper (https://computationalcommunication.org/ccr/article/view/98)
